{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gdtools
  version: "0.1.4"

source:
  fn: gdtools_0.1.4.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/gdtools_0.1.4.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/gdtools/gdtools_0.1.4.tar.gz

  md5: 62c2946391c7d1558e32025a6799cd0e

build:
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: htmltools, testthat, fontquiver (>= 0.2.0)
requirements:
  build:
    - r-base
    - r-rcpp
    - r-withr
    - posix               # [win]
    - {{native}}toolchain # [win]
    - gcc                 # [not win]
    - xorg-libxrender
    - xorg-libxext
    - xorg-libxdmcp
    - xorg-libxau
    - cairo [osx]

  run:
    - r-base
    - r-rcpp
    - r-withr
    - xorg-libxrender
    - xorg-libxext
    - xorg-libxdmcp
    - xorg-libxau
    - cairo [osx]

test:
  commands:
    - $R -e "library('gdtools')" # [not win]
    - "\"%R%\" -e \"library('gdtools')\"" # [win]

about:
  home: http://cran.r-project.org/web/packages/gdtools/index.html, http://github.com/davidgohel/gdtools
  license: GPL-3 | file LICENSE
  summary: Useful tools for writing vector graphics devices.
  license_family: GPL3
